### ISSUE TITLE
Error not showing on Submit

### ISSUE THREAD

**Issue by karimja** [daixianceng/formik-material-fields#3]
If i have a CheckboxGroupField and don't touch any of the text boxes and then press submit. The errors are not shown. If i check one of the checkboxes and uncheck it then the errors are shown. Is there a way this behaviour could be changed ? 

So instead of 

const message = this.state.dirty && getIn(errors, field.name);

i need 

const message = getIn(errors, field.name);

It would be good if there was a way to override this behaviour

**Comment by daixianceng** [comment]
Thanks for your report, `v0.0.5` was released, please upgrade
