### ISSUE TITLE
error messages display problem 

### ISSUE THREAD

**Issue by BennaceurHichem** [daixianceng/formik-material-fields#5]
I had a problme concern error displaying of textFields, errors are shown in a fixed place where I want to change their placement but I couldn't, I tried to display errors with ErrorMessage Component  of Formik but  it shows the errros message twice,one is due to the ErrorMessage of formik and another I couldn't understand their source but I think it's due to this library  I want to delete these messages and work with ErrorMessage component  to make the placement of error messages more customizable 

I had also the problem of displaying multiple errors in same placement 
How can I delete this message or customize it if the main cause of this message is this library 
this is my code : 
`import React from "react";
import { Formik, Field, Form, ErrorMessage } from "formik";
import * as Yup from "yup";
import { Input } from "@material-ui/core";
import { Button } from "@material-ui/core";
import { FormLabel } from "@material-ui/core";
import { FormGroup } from "@material-ui/core";
import Select from "@material-ui/core/Select";
import Avatar from "@material-ui/core/Avatar";
import CssBaseline from "@material-ui/core/CssBaseline";
import TextField from "@material-ui/core/TextField";
import FormControlLabel from "@material-ui/core/FormControlLabel";
import Checkbox from "@material-ui/core/Checkbox";
import Link from "@material-ui/core/Link";
import Grid from "@material-ui/core/Grid";
import Box from "@material-ui/core/Box";
import LockOutlinedIcon from "@material-ui/icons/LockOutlined";
import Typography from "@material-ui/core/Typography";
import { makeStyles } from "@material-ui/core/styles";
import Container from "@material-ui/core/Container";
import MenuItem from "@material-ui/core/MenuItem";
import { spacing } from '@material-ui/system';
import { FormikTextField, FormikSelectField } from "formik-material-fields";
import Icon from "@material-ui/core/Icon";
import Logo from 'assets/img/coronaWatchLogo.png'

const useStyles = makeStyles(theme => ({
  paper: {
    marginTop: theme.spacing(8),
    display: "flex",
    flexDirection: "column",
    alignItems: "center"
  },
  avatar: {
    margin: theme.spacing(1),
    backgroundColor: theme.palette.secondary.main
  },
  form: {
    width: "100%", // Fix IE 11 issue.
    marginTop: theme.spacing(1)
  },
  submit: {
    margin: theme.spacing(3, 0, 2)
  },

  customtextField: {
    variant: "outlined",
    margin: "normal",
    id: "email",
    label: "Email Address",
    name: "email",
    autoComplete: "email"
  }
}));

export default function FormikForm() {
  {
    const classes = useStyles();
    return (
      <Formik
        initialValues={{
          firstName: "",
         
          email: "",
          password: "",
          confirmPassword: "",
          poste: ""
        }}
        validationSchema={Yup.object().shape({
          firstName: Yup.string().required(""),

          email: Yup.string()
            .email("Email is invalid")
            .required(""),
          poste: Yup.string().required(""),
          password: Yup.string()
            .min(6, "Password must be at least 6 characters")
            .required(""),
          confirmPassword: Yup.string()
            .oneOf([Yup.ref("password"), null], "Passwords must match")
            .required("")
        })}
        
        onSubmit={fields => {
          alert("SUCCESS!! :-)\n\n" + JSON.stringify(fields, null, 4));
        }}
        render={({  status, touched,errors }) => (
          <div className={classes.paper}>
          
              <img src={Logo} style={{width:"100px",height:"100px"}}/>
          
            <Typography component="h1" variant="h5">
              Sign in
            </Typography>
       
            <Form className={classes.form} as={FormGroup}>
              <Grid
                container
                direction="column"
                justify="space-between"
                alignItems="center"
              >
                <div className="form-group">
                  <FormikTextField
                    as={TextField}
                    name="firstName"
                    type="text"
                    autoFocus
                    margin="normal"
                    id="firstName"
                    label="First name"
                    name="firstName"
                    autoComplete="firstName"
                    autoFocus
                    variant="outlined"
                  />
                </div>

                <div className="form-group">
                  <FormikTextField
                    as={TextField}
                    name="email"
                    type="text"
                    variant="outlined"
                    margin="normal"
                    required
                    id="email"
                    label="Email Address"
                   
                    autoComplete="email"
                    autoFocus
                  />
                </div>
                <div className="form-group">
                  <FormikTextField
                    as={TextField}
                    name="password"
                    type="password"
                    variant="outlined"
                    margin="normal"
                    required
                    id="password"
                    label="Password"
                    autoFocus
                  />
                </div>
                <div className="form-group">
                  <FormikTextField
                    as={TextField}
                    name="confirmPassword"
                    type="password"
                    variant="outlined"
                    margin="normal"
                    required
                    id="confirmPassword"
                    label="password Confirmation"
                    autoFocus
                  />
                </div>
                <div className="form-group">
                  <FormikSelectField
                    name="poste"
                    options={[
                      
                      { label: "moderateur", value: "moderateur" },
                      { label: "redacteur", value: "redacteur" },
                      { label: "agent_sante", value: "agent_sante" }
                    ]}
                    label="Poste"
                
                    variant="outlined"
                    required
                  />
                </div>
              </Grid>

              <div style={{marginTop:"2%"}}>

              <Button
            
            type="submit"
            variant="contained"
            color="primary"
            className={classes.button}
            icon={<Icon>send</Icon>}
          >
            Send
          </Button>
          <Button
            type="reset"
            variant="contained"
            className={classes.button}
          >
            Reset
          </Button>
              </div>
               
         
            </Form>
            

          </div>
        )}
        //fin Formik
      />
    );
  }
}
`

**Comment by daixianceng** [comment]
Edit this file in the library: `src\TextField\TextField.js`:

```diff
<MatTextField
-        {...props}
-        {...field}
        error={Boolean(message)}
        helperText={message || helperText}
+        {...props}
+        {...field}
        onChange={this.handleChange}
        onBlur={this.handleBlur}
      >
        {children}
</MatTextField>
```
Then in your code:

```diff
<FormikTextField
                as={TextField}
                name="confirmPassword"
                type="password"
                variant="outlined"
                margin="normal"
                required
                id="confirmPassword"
                label="password Confirmation"
                autoFocus
+             error={false}
+             helperText=""
/>
```

**Comment by BennaceurHichem** [comment]
I didn't find this code but I find this instead  in  es/TextFieldTextField.js in line 82 :

`  var message = getIn(touched, field.name) && getIn(errors, field.name);
      return React.createElement(MatTextField, _extends({}, props, field, {
        ...props,
        ...field,
        error: Boolean(message),
        helperText: message || helperText,
    
        onChange: this.handleChange,
        onBlur: this.handleBlur
      }), children);` 


I did this change, addinf ...props and ...filed as you see, than I added in my Textfields the error and helperText props but same problem, the error message steel showing

**Comment by daixianceng** [comment]
ok, it should be changes `es\TextField\TextField.js` and `lib\TextField\TextField.js`.

```diff
return React.createElement(MatTextField, _extends({
+        error: Boolean(message),
+        helperText: message || helperText,
}, props, field, {
-        error: Boolean(message),
-        helperText: message || helperText,
        onChange: this.handleChange,
        onBlur: this.handleBlur
      }), children);
```
After modifed `node_modules`, you needs **restart the project**

**Comment by BennaceurHichem** [comment]
Same Error persist I do what you reccomand and I also try without and with error and helperText props and nothing changes, I restarted the project more than one tile but nothing changes
 `  return _react.default.createElement(_TextField.default,
 _extends({ 
        error: Boolean(message),
        helperText: message || helperText,}, 
props, field, {
        onChange: this.handleChange,
        onBlur: this.handleBlur
      }), children);`

**Comment by BennaceurHichem** [comment]
the problem is related with material ui error message styling, I detect the problem by verifying the style of the error message and changing the position of the error message, so the problem is related with material-ui and it's solved by customizsing postion of the message class css style
